---
title: "Dive behavior"
format: html
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
---

First, read in and prep the data.

```{r}
#| label: setup
#| message: false

library(tidyverse)
library(nlme)
source(here::here("R/dives.R"))
source(here::here("R/find_next.R"))

recording <- read_rds(here::here("output/recording_calib.rds"))
dive_summ <- read_rds(here::here("output/processed_dive_summaries.rds"))

#read in dive type data (done manually)
dive_type <- read_csv(here::here("data/manual-dive-type.csv")) %>% 
  select(-c(AcousticsUsed, Notes)) %>% 
  mutate(ID = 1,
         Benthic_Pelagic_int = unclass(factor(Benthic_Pelagic, 
                                              levels = c("Benthic", 
                                                         "Pelagic"))),
         Rest_Forage_Travel_int = unclass(factor(Rest_Forage_Travel, 
                                                 levels = c("Rest", 
                                                            "Forage",
                                                            "Travel")))) 

clicks_by_dive <- read_csv(here::here("data/sw/clicks_by_dive.csv")) %>% 
  #connect recording with the correct dive id 
  mutate(end_calib = recording$end_calib[-nrow(recording)],
         dive_id = dive_summ$dive_id[find_next(end_calib, dive_summ$end)], 
         sw_yn = sw_yn == "y") %>% 
  select(-c(clickmanual_complete, buzz, notes, duration_min, duration_sec)) %>% 
  left_join(select(dive_type, dive_id, Rest_Forage_Travel_int, ID),
            by = "dive_id") 

```

Are there differences in the dive characteristics when sw are present?

```{r}
model_dives <- clicks_by_dive %>% 
  # filter(Rest_Forage_Travel_int == 2) %>% 
  mutate(hours_elapsed = as.numeric(start_time - start_time[1], unit = "hours")) %>% 
  left_join(select(dive_summ, 
                   dive_id, 
                   bottom_duration_min, 
                   duration_min,
                   descent_rate_ms), 
            by = "dive_id")

# dive duration model
bottom_dur <- gls(bottom_duration_min ~ sw_yn, 
                  model_dives,
                  correlation = corCAR1(form = ~ hours_elapsed))
summary(bottom_dur)

# binned ACF for each model
irreg_acf <- function(mod) {
  r <- residuals(mod, 
                 type = ifelse(is(mod, "gls"), 
                               "normalized",
                               "pearson"))
  t <- model_dives$hours_elapsed
  
  pairs <- expand_grid(i = seq_along(r), j = seq_along(r)) %>% 
    filter(j > i) %>% 
    mutate(lag = abs(t[i] - t[j]),
           prod = r[i] * r[j]) %>% 
    filter(lag <= 24)
  
  bin_width = 0.5
  pairs %>% 
    mutate(lag_bin = floor(lag / bin_width) * bin_width + bin_width / 2) %>% 
    group_by(lag_bin) %>% 
    summarize(acf = mean(prod), n = n()) %>% 
    slice(-n()) %>% 
    ggplot(aes(lag_bin, acf)) +
    geom_hline(yintercept = 0 ) +
    geom_hline(yintercept = c(-1.96, 1.96) / sqrt(length(t)),
               linetype = "dashed", color = "blue") +
    geom_col()
}
#irreg_acf(dive_dur_lm)
irreg_acf(bottom_dur)
intervals(bottom_dur)

# descent rate model
desc_rate <- gls(descent_rate_ms ~ sw_yn, 
                model_dives,
                correlation = corCAR1(form = ~ hours_elapsed))
summary(desc_rate)

# binned ACF for each model
irreg_acf(desc_rate)
intervals(desc_rate)

# total duration rate model
total_dur <- gls(duration_min ~ sw_yn, 
                model_dives,
                correlation = corCAR1(form = ~ hours_elapsed))
summary(total_dur)

# binned ACF for each model
irreg_acf(total_dur)
intervals(total_dur)
```

Dive duration is on average 1-2 mins longer when sperm whales are present.

```{r}
model_dives %>% 
  ggplot(aes(x = sw_yn, 
             y = bottom_duration_min)) +
  geom_jitter(color = "gray40", alpha = 0.1) +
  geom_boxplot(alpha = 0.7) +
  labs(x = "Sperm whales present", 
       y = "Dive bottom time (mins)") + 
  theme_minimal()
```

```{r}
daily_dives <- dive_summ %>% 
  left_join(dive_type, by = "dive_id") %>% 
  drop_na(Rest_Forage_Travel_int) %>% 
  mutate(date = as_date(start)) %>% 
  group_by(date, Rest_Forage_Travel) %>% 
  summarize(count = n(), .groups = "drop_last") %>% 
  mutate(prop = count / sum(count)) %>% 
  ungroup()
daily_dives %>% 
  ggplot(aes(date, prop, fill = Rest_Forage_Travel)) +
  geom_col() + 
  scale_fill_manual(values = c("Rest" = "turquoise3", 
                               "Forage" = "orange", 
                               "Travel" = "lightgoldenrod"
  )) +
  labs(x = NULL, 
       y = "Proportion of dives", 
       fill = "Behavior") + 
  theme_minimal()
```
